export const defaultRow = {
  rowNumber: 0,
  dbId: "",
  Discipline: "",
  ElementType: "",
  TypeName: "",
  Description: "",
  Length: "",
  Width: "",
  Height: "",
  Perimeter: "",
  Area: "",
  Thickness: "",
  Volume: "",
  Level: "",
  Material: "",
  EnergyConsumption: "",
  CarbonFootprint: "",
  WaterConsumption: "",
  LifeCycleStage: "",
  LEEDCategory: "",
  LEEDCredit: "",
};
