export const defaultRow = {
    rowNumber: 0,
    dbId: "",
    Code: "",
    Discipline: "",
    ElementType: "",
    TypeName: "",
    Description: "",
    Length: "",
    Width: "",
    Height: "",
    Perimeter: "",
    Area: "",
    Thickness: "",
    Volume: "",
    Level: "",
    Material: "",
    Unit: "",
    Quantity: "",
    UnitPrice: "",
    TotalCost: "",
}