export const defaultRow = {
  rowNumber: 0,
  dbId: "",
  Discipline: "",
  ElementType: "",
  TypeName: "",
  Description: "",
  Length: "",
  Width: "",
  Height: "",
  Perimeter: "",
  Area: "",
  Thickness: "",
  Volume: "",
  Level: "",
  Material: "",
  PlanedConstructionStartDate: "",
  PlanedConstructionEndDate: "",
  RealConstructionStartDate: "",
  RealConstructionEndDate: "",
};
